server:
  port: 8081
spring:
  datasource:
    username: root
    password: huyouni
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/class_cost?characterEncoding=utf-8&serverTimezone=GMT%2B8
    type: com.alibaba.druid.pool.DruidDataSource
  thymeleaf:
    mode: HTML5
    encoding: utf-8
    cache: false
# 打印日志
logging:
  level:
    com.zys.class_cost_sb: debug
debug: false