server:
  port: 8081
spring:
  datasource:
    username: root
    password: huyouni
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/class_cost?characterEncoding=utf-8&serverTimezone=GMT%2B8
    type: com.alibaba.druid.pool.DruidDataSource
  thymeleaf:
    mode: HTML5
    encoding: utf-8
    cache: false
# 打印日志
logging:
  level:
    com.zys.class_cost_sb: debug
debug: false

alipay:
  appId: 2016101600703982
  merchantPrivateKey: MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDLkSz3lIRtemxuaBAeG9SG3FlVxoLh+iz3Qmkb/5Y/EKuBBIE+qxLtVX2VQy3d41W4LViglwh66WnelPFrUU6qQWpUgqwFfMMgUAflEdCvGF9/I33UhF+it8poftfC9kRRdPBJD39Wr33XbKyB/9zvRWviGQ0V9Xdj1+MGjAh/mvMdAU8vT1W6JioJLNKLBXxR9LsdPfaYCuydGo+ePa/8IBn7PZJEpMADt7AijOg2/1x13Icjg/NFx8SnPs2UuV2aFWe05OikbOw08pCrOh0XGUhRfNsn5Bfo5OtadajYCvUT8zPOqFWNMpGJb0t2ClGyi/UXepvrwY99PRjAZ5fjAgMBAAECggEAYMP83R+DJ8tnGcBr0PQnvYenC6gWdTcIAu1Vq5J+KDJTZDvw+Ao4MAtQbBCIEA7No4QiuguxY0PrKHwimoIG49W+preK7/zTgFuqtRAX4/OxCW2klc3q7B1zoOKSy8FmzlXJFuHABUPcjPfCtPUcX7zfQJXp64NIonRwHZ+ZNpZm8mkfAuiwXryG7cD76yHKoyDASMMgkvhYh1I8Iqt60Dg2MHO0sR/C1VlRGQu6I49QsNgbos4akKwvHZjVFKc5Nz4fXcIwT9GI5a2ROwqYn1PU51mqbNeIK4t89lqxOAWc5f1yHNRIZj4H/PLtUUVMXIGnQvRJF3b4p42gpVbAaQKBgQDz6GV1whjt/2XYHufDOjs9cA5Zby6X4IP9xx/lPYnylbuCntsi9b53NH4FmNu9Dd0I1g7zQ6Gz3FxyIw+i1G4fbiYkMklnOpg/Z//eqr2aBGJIwMrm8MMPLYesJSiw1T+9mvhOuEc32UGPReRuNsK4dWDGKVG5dpM0J9kdE3uC7QKBgQDVqMmPUiWB+QQiM7O+ftXI7+yMrYwTfB17V252gFvuiwr1pKI54zjJ3VEqIMwJz8okfL+xvvM9DAeBiemK7t5Fhb/LXOz09a+PEWEuMkDGA3e2oAhUfMwjkdPar0raKLgP9TWh/T0fGHZxXVzPp1++oVTuHz8hByPSKaFIuR0cDwKBgFOCw5JxNaXvZ0h7NHFUs8nSXydh+PsJZUfz8MjFrEDB4aTUjUVIDMG12FxEPSBa6c5HtHC4PFpf3cs6k/T1dQsP5MFJ8nYEyvISwrnTjf14+MneMNqnnrHIrgZT5r29FgjuUYxqbgACQ/8xOAhAeaU8kzjmFtRAdCBMcHsTG5v1AoGBAMfspI5jg41XAbMvReXesRTQzDvmuMgSv1OGwGpKObvAh4TLhLE+GQlq+mO9RK95q+Dwij88OkbJVsyzy8ChO4M6X/le/qtIqfnpfVHI3CttWzucC69jB3HRJrfehuAUcgccoA7v852BOnNhtVLpfwHV3K7ktiGlmLMzGSP/c2mpAoGAdI71RczN9kbnMoINvUv7sl/1iCMZI/7s0jRDqEPra9SrD7eRpX+1IC1E+HcmvnD7S2Z6we1X3FGoZT8QrERq0yGMoYsWP3o/vz7WP3UdhAXsv6952Sc6/t8fm4FVHAYQSSDWhJhaF/AxLiN7XGAThLNQFmLuUkwZdZiq6aSGh5g=
  aliPayPublicKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAo9ZHPLa
  notifyUrl: http://0c58fa17.ngrok.io/pay/aliPayAsyncBack
  returnUrl: http://0c58fa17.ngrok.io/pay/aliPaySyncBack
  signType: RSA2
  charset: utf-8
  gatewayUrl: https://openapi.alipaydev.com/gateway.do
  logPath: d:\log\
  timeoutExpress: 10m